groups:
  - name: alert.rules
    rules:
    - alert: HighCPUUsage
      expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
      for: 1m
      labels:
        severity: "warning"
      annotations:
        summary: "High CPU usage detected"

    - alert: DiskFull
      expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
      for: 2m
      labels:
        severity: "critical"
      annotations:
        summary: "Disk almost full"
